class_name PythonBridgeWrapperGenerator
extends RefCounted
## Generates a GDScript wrapper class for a Python script.
##
## Input: the introspection schema returned by
## PythonBridge.introspect_script() (AST-based, from the Python server).
## Output: a deterministic .gd file that calls PythonBridge.call_script().
##
## Rules (verbindlich):
##   - Generated files carry a marker header; only marker files are ever
##     overwritten. Manual code is never touched.
##   - The output is deterministic: same input schema -> identical bytes.
##   - Type hints are documentation only (Variant params, hint comments).
##   - Python defaults are preserved as "unset" checks (static var sentinel),
##     so Python-side defaults stay authoritative.
##   - class_name collisions against the project global class list abort
##     with a visible error instead of silently generating broken code.

const MARKER := "# ===== GENERATED BY PYTHON BRIDGE - DO NOT EDIT ====="

static func is_generated(path: String) -> bool:
	if not FileAccess.file_exists(path):
		return false
	var f := FileAccess.open(path, FileAccess.READ)
	if f == null:
		return false
	var first := f.get_line()
	f.close()
	return first.strip_edges().begins_with(MARKER)

## Generates the wrapper source. `schema` is the Array of function dicts
## from introspect_script(); `script_id` and `instance_name` are embedded.
## Returns {"ok": true, "code": String} or {"ok": false, "error": String}.
static func generate(schema: Array, script_id: String, instance_name := "") -> Dictionary:
	if instance_name == "":
		instance_name = PythonBridgeConfig.DEFAULT_INSTANCE
	var cls_name := _class_name_for(script_id)
	if _class_name_taken(cls_name):
		return {"ok": false, "error":
			"class_name '%s' is already used in this project. Rename the Python file or remove the conflicting class." % cls_name}

	var lines: Array[String] = []
	lines.append(MARKER)
	lines.append("# Source: python script '%s'" % script_id)
	lines.append("# Instance: '%s'" % instance_name)
	lines.append("# Regenerate: PythonBridge editor dock -> \"Generate wrapper\"")
	lines.append("")
	lines.append("extends RefCounted")
	lines.append("class_name %s" % cls_name)
	lines.append("")
	lines.append("const SCRIPT_ID := %s" % _quote(script_id))
	lines.append("const INSTANCE_NAME := %s" % _quote(instance_name))
	lines.append("static var _unset := RefCounted.new()")
	lines.append("")

	# Deterministic order: alphabetical by function name.
	var funcs := schema.duplicate()
	funcs.sort_custom(_by_name)

	for fn in funcs:
		_append_function(lines, fn)

	lines.append("")
	lines.append("# End of generated wrapper.")
	return {"ok": true, "code": "\n".join(lines) + "\n"}

static func _append_function(lines: Array[String], fn: Dictionary) -> void:
	var name := str(fn.get("name", ""))
	if name == "":
		return
	var params: Array = fn.get("params", [])
	var doc := str(fn.get("docstring", ""))
	var ret_hint := str(fn.get("returns", ""))

	# --- method signature (Variant params, sentinel defaults) ---
	var sig_params: Array[String] = []
	for p in params:
		var pname := _sanitize_ident(str(p.get("name", "arg")))
		if bool(p.get("has_default", false)):
			sig_params.append("%s = _unset" % pname)
		else:
			sig_params.append(pname)
	sig_params.append("timeout_sec := 30.0")
	lines.append("## " + _doc_first_line(doc))
	if ret_hint != "":
		lines.append("## Returns hint: %s (hint only, not a runtime guarantee)" % ret_hint)
	lines.append("func %s(%s) -> PythonBridgeResult:" % [name, ", ".join(sig_params)])

	# --- build args/kwargs ---
	var posonly: Array[String] = []
	var kwargs_lines: Array[String] = []
	var var_name := ""
	var kw_name := ""
	for p in params:
		var pname := _sanitize_ident(str(p.get("name", "arg")))
		match str(p.get("kind", "pos")):
			"posonly":
				posonly.append(pname)
			"var":
				var_name = pname
			"kw":
				kw_name = pname
			"kwonly":
				kwargs_lines.append("if %s != _unset:\n\tkwargs[%s] = %s" % [pname, _quote(pname), pname])
			_:
				if bool(p.get("has_default", false)):
					kwargs_lines.append("if %s != _unset:\n\tkwargs[%s] = %s" % [pname, _quote(pname), pname])
				else:
					kwargs_lines.append("kwargs[%s] = %s" % [_quote(pname), pname])

	var args_lines: Array[String] = []
	if not posonly.is_empty():
		args_lines.append("var args: Array = []")
		for pname in posonly:
			args_lines.append("if %s != _unset:\n\targs.append(%s)" % [pname, pname])
		args_lines.append("")
	if var_name != "":
		args_lines.append("if %s != _unset and %s is Array:\n\targs.append_array(%s)" % [var_name, var_name, var_name])

	# merge kwargs dict
	if kw_name != "":
		kwargs_lines.append("if %s != _unset and %s is Dictionary:\n\tfor k in %s:\n\t\tkwargs[k] = %s[k]" % [kw_name, kw_name, kw_name, kw_name])

	var body: Array[String] = []
	body.append("var kwargs: Dictionary = {}")
	if not args_lines.is_empty():
		body.append("")
		body.append_array(args_lines)
	for line in kwargs_lines:
		body.append(line)
	body.append("return await PythonBridge.call_script(")
	body.append("\tSCRIPT_ID, %s, args, kwargs, INSTANCE_NAME, timeout_sec)" % _quote(name))
	for line in body:
		lines.append("\t" + line)
	lines.append("")

static func _class_name_for(script_id: String) -> String:
	# Build a valid PascalCase GDScript identifier: separators ("_", "-",
	# ".", spaces, ...) act as word boundaries, so "mein_skript" and
	# "mein-skript" both become "MeinSkript".
	var base := script_id.get_file().get_basename()
	var pascal := ""
	var cap_next := true
	for c in base:
		if c == "_":
			cap_next = true
		elif c.is_valid_identifier():
			pascal += c.to_upper() if cap_next else c
			cap_next = false
		else:
			cap_next = true
	if pascal == "":
		pascal = "Script"
	return "PyBridge" + pascal

static func _class_name_taken(cls_name: String) -> bool:
	if ClassDB.class_exists(cls_name):
		return true
	for entry in ProjectSettings.get_global_class_list():
		if str(entry.get("class", "")) == cls_name:
			return true
	return false

static func _sanitize_ident(s: String) -> String:
	if s == "":
		return "arg"
	var out := ""
	for c in s:
		out += c if (c == "_" or c.is_valid_identifier()) else "_"
	return out

static func _quote(s: String) -> String:
	return "\"" + s.replace("\\", "\\\\").replace("\"", "\\\"") + "\""

static func _doc_first_line(doc: String) -> String:
	if doc == "":
		return "Wrapper for a Python function."
	var first := doc.strip_edges().split("\n")[0]
	return first if first != "" else "Wrapper for a Python function."

static func _by_name(a: Dictionary, b: Dictionary) -> bool:
	return str(a.get("name", "")) < str(b.get("name", ""))